### ISSUE TITLE
npm ERR!

### ISSUE THREAD

**Issue by iwwz** [wxsms/daily-signer#3]
npm WARN daily-sign@0.0.1 No repository field.
npm ERR! Linux 4.19.2-aml-s9xxx
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@2.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.2.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/JD/npm-debug.log

**Comment by wxsms** [comment]
你的node是什么版本？貌似canvas 2.2.0 在某些版本上会 build 失败。如果你是 6 或者 7，升级 node 试试。

https://github.com/Automattic/node-canvas/issues/1319#issuecomment-444146174

**Comment by iwwz** [comment]
root@Wins-N1-2:~# node -v
v8.10.0
root@Wins-N1-2:~# npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/lib
└── n@2.1.12 

root@Wins-N1-2:~# 
@wxsms

**Comment by wxsms** [comment]
那我就不知道了。我这里install没有问题。如果你想debug并找到了原因，可以提个PR
